-- Active: 1728316517915@@127.0.0.1@3306@test
--Select
SELECT INDIVIDUAL.CUST_ID,INDIVIDUAL.FIRST_NAME,INDIVIDUAL.`LAST_NAME`,customer.`POSTAL_CODE` FROM customer,INDIVIDUAL WHERE `FIRST_NAME`= 'John' AND `POSTAL_CODE`=01887 AND `LAST_NAME`='Spencer' ;

--SELECT `CUST_ID`,`OPEN_BRANCH_ID` as branch_id, sum(ROUND(AVAIL_BALANCE,2)) as total FROM ACCOUNT GROUP BY `CUST_ID`,OPEN_BRANCH_ID;
--Filter/WHERE

SELECT `CUST_ID`,`OPEN_BRANCH_ID`, sum(ROUND(AVAIL_BALANCE,2)) as total FROM ACCOUNT GROUP BY `CUST_ID`,OPEN_BRANCH_ID HAVING `OPEN_BRANCH_ID`=2;
--Sub Select
SELECT * FROM ( SELECT CUST_ID ,sum(ROUND(AVAIL_BALANCE,2)) as Total,OPEN_BRANCH_ID from ACCOUNT group by `CUST_ID`,OPEN_BRANCH_ID ) as balance WHERE total>5000;
--Join
SELECT account.CUST_ID, sum(ROUND(AVAIL_BALANCE,2)) as total ,First_Name,Last_Name,BIRTH_DATE FROM ACCOUNT JOIN INDIVIDUAL on ACCOUNT.CUST_ID=INDIVIDUAL.CUST_ID GROUP BY ACCOUNT.CUST_ID HAVING total>5000;

--Multi Join
SELECT 
    account.CUST_ID, 
    SUM(ROUND(AVAIL_BALANCE, 2)) AS total, 
    FIRST_NAME, 
    LAST_NAME, 
    BIRTH_DATE, 
    OPEN_BRANCH_ID, 
    BRANCH.NAME, 
    BRANCH.ADDRESS 
FROM 
    ACCOUNT 
JOIN 
    INDIVIDUAL ON INDIVIDUAL.CUST_ID = account.CUST_ID 
JOIN 
    BRANCH ON BRANCH.BRANCH_ID = account.OPEN_BRANCH_ID 
GROUP BY 
    account.CUST_ID, 
    FIRST_NAME, 
    LAST_NAME, 
    BIRTH_DATE, 
    OPEN_BRANCH_ID, 
    BRANCH.NAME, 
    BRANCH.ADDRESS;


--Count
