# Generated by Django 5.1.4 on 2025-02-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
