# Generated by Django 5.1.4 on 2025-01-16 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('checkbox', models.BooleanField(default=False)),
                ('photo', models.ImageField(default=None, null=True, upload_to='photos/')),
            ],
        ),
    ]
