# Generated by Django 5.1.4 on 2025-03-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_post_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='viewed_users',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
