# Generated by Django 5.1.5 on 2025-01-26 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
