# Generated by Django 5.1.4 on 2025-01-27 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_employee_is_employed'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employed_joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_employed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
