# Generated by Django 5.1.4 on 2025-01-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_employee_employed_joining_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employed_joining_date_joined',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
