# Generated by Django 5.1.4 on 2025-01-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_employee_employed_joining_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employed_joining_date',
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
