# Generated by Django 5.1.4 on 2025-01-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_employee_employed_joining_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_files',
            field=models.FileField(blank=True, null=True, upload_to='files_uploads/'),
        ),
    ]
