# Generated by Django 5.1.4 on 2025-01-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_employee_emp_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
