# Generated by Django 5.1.4 on 2025-01-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_employee_emp_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
