# Generated by Django 5.1.4 on 2025-01-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_employee_emp_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='emp_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
