# Generated by Django 5.1.4 on 2025-01-28 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_emp_name_employee_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='emp_name',
        ),
    ]
