# Generated by Django 5.1.4 on 2025-02-22 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_student_user_alter_student_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='checkbox',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
        migrations.AddField(
            model_name='student',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
