# Generated by Django 5.1.4 on 2025-01-16 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(default=None, null=True, upload_to='newPhotos/'),
        ),
    ]
